a=input("How many family members you have: ")
b=input("What is your father's name: ")
c=input("what your your mother's name:")
d=input("What is your sister's or your brother's name: ")
e=input("Your family members are")
print(b,c,d)
